### **Importing Libraries**

In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
### importing Data
df=pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [3]:
# Independent & dependent data Split
x=df.iloc[:,3:13]
y=df.iloc[:,13]

In [4]:
## First 5 rows of x data
x.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [5]:
## First 5 rows of y data
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [6]:
## Coverting Geography categorical data using Dummy variable
geography=pd.get_dummies(x['Geography'],drop_first=True)
## First 5 rows of geography

geography.head()

Germany  Spain
0        0      0
1        0      1
2        0      0
3        0      0
4        0      1

In [7]:
## Coverting Gender categorical data using Dummy variable
gender=pd.get_dummies(x['Gender'],drop_first=True)
## First 5 rows of gender data

gender.head()

Male
0     0
1     0
2     0
3     0
4     0

In [8]:
## Concatinating x data with gender and geography variables using pd.concat
x=pd.concat([x,geography,gender],axis=1)

In [9]:
## First 5 rows of x data after concatinating

x.head()

CreditScore Geography  Gender  Age  ...  EstimatedSalary  Germany  Spain  Male
0          619    France  Female   42  ...        101348.88        0      0     0
1          608     Spain  Female   41  ...        112542.58        0      1     0
2          502    France  Female   42  ...        113931.57        0      0     0
3          699    France  Female   39  ...         93826.63        0      0     0
4          850     Spain  Female   43  ...         79084.10        0      1     0

[5 rows x 13 columns]

In [10]:
## Droping Unrequired data (Gender,Geography)
x=x.drop(['Gender','Geography'],axis=1)

In [11]:
## First 5 rows of x data after droping 

x.head()

CreditScore  Age  Tenure    Balance  ...  EstimatedSalary  Germany  Spain  Male
0          619   42       2       0.00  ...        101348.88        0      0     0
1          608   41       1   83807.86  ...        112542.58        0      1     0
2          502   42       8  159660.80  ...        113931.57        0      0     0
3          699   39       1       0.00  ...         93826.63        0      0     0
4          850   43       2  125510.82  ...         79084.10        0      1     0

[5 rows x 11 columns]

In [12]:
## Spliting x & y data using sklearn train_test_split 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [13]:
## First 5 rows of x_train data

x_train.head()

CreditScore  Age  Tenure  ...  Germany  Spain  Male
7389          667   34       5  ...        0      1     0
9275          427   42       1  ...        1      0     1
2995          535   29       2  ...        0      0     0
5316          654   40       5  ...        0      1     1
356           850   57       8  ...        0      1     0

[5 rows x 11 columns]

In [14]:
## First 5 rows of x_test data

x_test.head()

CreditScore  Age  Tenure  ...  Germany  Spain  Male
9394          597   35       8  ...        1      0     0
898           523   40       2  ...        0      0     0
2398          706   42       8  ...        0      1     0
5906          788   32       4  ...        0      0     1
2343          706   38       5  ...        1      0     1

[5 rows x 11 columns]

In [15]:
## First 5 rows of y_train data

y_train.head()

7389    0
9275    0
2995    0
5316    0
356     0
Name: Exited, dtype: int64

In [16]:
## First 5 rows of y_test data

y_test.head()

9394    0
898     1
2398    0
5906    0
2343    0
Name: Exited, dtype: int64

In [17]:
### Data needs to scale so here using StandardScaler
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [18]:
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [19]:
## x_train data after scaling

x_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [20]:
## x_test data after scaling
x_test

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]])

In [21]:
## x_train data size
x_train.shape

(8000, 11)

# **ANN**

In [22]:
### Importing keras libraries
import keras
from keras.models import Sequential
from keras.layers import Dense,Activation,Embedding,Flatten,LeakyReLU,BatchNormalization
from keras.layers import Dropout
from keras.activations import relu,sigmoid

In [23]:
### Performing HyperParameter
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import  GridSearchCV

In [34]:
def create_model(layers,activation):
  model=Sequential()
  for i,nodes in enumerate(layers):
    if i==0:
      model.add(Dense(nodes,input_dim=x_train.shape[1]))
      model.add(Activation(activation))
      model.add(Dropout(0.3))
    else:
      model.add(Dense(nodes))
      model.add(Activation(activation))
      model.add(Dropout(0.3))
  model.add(Dense(units=1,activation='sigmoid',kernel_initializer='glorot_uniform'))
  model.compile(optimizer='adam',metrics=['accuracy'],loss='binary_crossentropy')
  return model


In [40]:
model=KerasClassifier(build_fn=create_model,verbose=2)
model

In [41]:
layers=[(150,), (160,100), (140,100,500)]
activations=['sigmoid','relu']
param_grid=dict(layers=layers,activation=activations,batch_size=[128,256],epochs=[30])

In [42]:
grid = GridSearchCV(estimator=model, param_grid=param_grid)


In [43]:
grid

GridSearchCV(cv=None, error_score=nan,
             estimator=<tensorflow.python.keras.wrappers.scikit_learn.KerasClassifier object at 0x7f20756a9358>,
             iid='deprecated', n_jobs=None,
             param_grid={'activation': ['sigmoid', 'relu'],
                         'batch_size': [128, 256], 'epochs': [30],
                         'layers': [(150,), (160, 100), (140, 100, 500)]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [44]:
grid_result = grid.fit(x_train, y_train)


Epoch 1/30
50/50 - 0s - loss: 0.5608 - accuracy: 0.7206
Epoch 2/30
50/50 - 0s - loss: 0.4754 - accuracy: 0.7975
Epoch 3/30
50/50 - 0s - loss: 0.4653 - accuracy: 0.8025
Epoch 4/30
50/50 - 0s - loss: 0.4531 - accuracy: 0.8025
Epoch 5/30
50/50 - 0s - loss: 0.4485 - accuracy: 0.8041
Epoch 6/30
50/50 - 0s - loss: 0.4469 - accuracy: 0.8027
Epoch 7/30
50/50 - 0s - loss: 0.4454 - accuracy: 0.8041
Epoch 8/30
50/50 - 0s - loss: 0.4396 - accuracy: 0.8048
Epoch 9/30
50/50 - 0s - loss: 0.4398 - accuracy: 0.8050
Epoch 10/30
50/50 - 0s - loss: 0.4421 - accuracy: 0.8050
Epoch 11/30
50/50 - 0s - loss: 0.4428 - accuracy: 0.8059
Epoch 12/30
50/50 - 0s - loss: 0.4389 - accuracy: 0.8078
Epoch 13/30
50/50 - 0s - loss: 0.4381 - accuracy: 0.8064
Epoch 14/30
50/50 - 0s - loss: 0.4382 - accuracy: 0.8097
Epoch 15/30
50/50 - 0s - loss: 0.4385 - accuracy: 0.8120
Epoch 16/30
50/50 - 0s - loss: 0.4361 - accuracy: 0.8106
Epoch 17/30
50/50 - 0s - loss: 0.4390 - accuracy: 0.8047
Epoch 18/30
50/50 - 0s - loss: 0.4343 - 

In [48]:
print(grid_result.best_params_)

{'activation': 'relu', 'batch_size': 128, 'epochs': 30, 'layers': (160, 100)}


In [50]:
print(grid_result.best_score_)

0.8600000023841858


In [51]:
### Prediction
y_pred=grid.predict(x_test)
y_pred

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
16/16 - 0s


array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [52]:
y_pred=(y_pred>0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [53]:
### Accuracy

In [54]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [55]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[1517,   78],
       [ 200,  205]])

In [56]:
score=accuracy_score(y_test,y_pred)
score

0.861